apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nsem9ctq8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nsem9ctq8-go 
  name: nsem9ctq8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nsem9ctq8-go 
